/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("model.glb");

  useEffect(() => {
    materials.rastMat.envMapIntensity = 1.1;
    materials.rastMat.map.anisotropy = 128;
  }, []);

  return (
    <group {...props} dispose={null}>
      <mesh
        scale={[0.15, 0.15, 0.15]}
        geometry={nodes.angleterre003.geometry}
        material={materials.rastMat}
      />
    </group>
  );
}

useGLTF.preload("model.glb");

export default Model;
